volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: INFO
  DATABASE_HOST: db
  DATABASE_NAME: vapor_database
  DATABASE_USERNAME: vapor_username
  DATABASE_PASSWORD: vapor_password
  # TZ: Europe/Berlin
  # TIBBER_API_KEY: YOUR-API-KEY

services:
  app:
    image: ghcr.io/juliankahnert/homeautomation:main
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./docker-volumes/home-automation:/tmp
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
  migrate:
    image: ghcr.io/juliankahnert/homeautomation:main
    environment:
      <<: *shared_environment
    depends_on:
      - db
    volumes:
      - ./docker-volumes/home-automation:/tmp
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: ghcr.io/juliankahnert/homeautomation:main
    environment:
      <<: *shared_environment
    depends_on:
      - db
    volumes:
      - ./docker-volumes/home-automation:/tmp
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: mysql:9
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: vapor_username
      MYSQL_PASSWORD: vapor_password
      MYSQL_DATABASE: vapor_database
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
